crism_browse_products = [
     ("TRU", "True color composite (R600, R530, R440)",
     "Enhanced true color representation after photometric + atmospheric correction"),
    ("VNA", "VNIR albedo (R770, R770, R770)",
     "Photometrically corrected 770 nm reflectance; morphology + albedo contrast"),
    ("TAN", "Tandem color composite (R2529, IRA, R770)",
     "Visible-to-IR enhanced false color; broad mineral + morphology overview"),
    ("IRA", "IR albedo (R1300, R1300, R1300)",
     "Photometrically corrected 1.33 µm reflectance; IR brightness / morphology"),
    ("FAL", "False color IR composite (R2529, R1506, R1080)",
     "Highlights mafic vs clay vs carbonate distributions"),
    ("FEM", "Fe mineralogy (BD530_2, SH600_2, BDI1000VIS)",
     "Sensitive to ferric/ferrous phases, dust coatings, and texture; red = ferric oxides"),
    ("FM2", "Fe mineralogy v2 (BD530_2, BD920_2, BDI1000VIS)",
     "Enhanced sensitivity to olivine, pyroxene, nanophase ferric oxides"),
    ("MAF", "Mafic mineralogy (OLINDEX3, LCPINDEX2, HCPINDEX2)",
     "Olivine + pyroxene discrimination; LCP vs HCP separation"),
    ("HYD", "Hydrated mineralogy (SINDEX2, BD2100_2, BD1900_2)",
     "Bound water + sulfates; mono/polyhydrated sulfate discrimination"),
    ("PHY", "Phyllosilicates (D2300, D2200, BD1900r2)",
     "OH-bearing minerals: Fe/Mg vs Al phyllosilicates + hydration state"),
    ("PFM", "Fe/Mg phyllosilicates (BD2355, D2300, BD2290)",
     "Fe/Mg smectites, chlorite, epidote, Mg carbonates, Ca/Fe carbonates"),
    ("PAL", "Al phyllosilicates (BD2210_2, BD2190, BD2165)",
     "Al-smectites, kaolinite group, hydrated silica, alunite"),\
    ("HYS", "Hydrated silica / OH minerals (MIN2250, BD2250, BD1900r2)",
     "Hydrated silica vs Al-OH separation; jarosite detection"),
    ("ICE", "Water / CO2 ice (BD1900_2, BD1500_2, BD1435)",
     "Water ice vs CO2 ice discrimination"),
    ("IC2", "Ice composite v2 (R3920, BD1500_2, BD1435)",
     "Ice detection with silicate normalization at 3.9 µm"),
    ("CAR", "Carbonates (D2300, BD2500H2, BD1900_2)",
     "Mg carbonates vs phyllosilicates; hydration context"),
    ("CR2", "Carbonates v2 (MIN2295_2480, MIN2345_2537, CINDEX2)",
     "Mg vs Fe/Ca carbonate discrimination"),
    ("CHL", "Chloride-related deposits (ISLOPE, BD3000, IRR2)",
     "Inferred chloride deposits; relatively dry, spectrally distinct surfaces"),
]
